### ISSUE TITLE
Errors list not cleared after Closing Active tab or Opened files

### ISSUE THREAD

**Issue by tamdilip** [lifeart/vscode-ember#10]
- Need a config to list lint errors under "problems" tab, only for active focused file or opened files.

**Comment by lifeart** [comment]
Hi @tamdilip, in my understanding, it's area of vscode internal logic itself, do you have any documentation, pointing to implementation inside extension?

**Comment by tamdilip** [comment]
> Hi @tamdilip, in my understanding, it's area of vscode internal logic itself, do you have any documentation, pointing to implementation inside extension?

Not sure on the documentation part, will try to dig on that.
But observed "[ESLint VScode Extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)" clearing the errors from "problems" tab when the opened files are closed.

For now I'm good with the filter option to "Show Active Files Only", which helps my need :) !!
