### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Depgit** [lifeart/vscode-ember#16]
- Issue Type: `Bug`
- Extension Name: `vscode-ember-unstable`
- Extension Version: `2.0.10`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.54.1`

:warning: 
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 12920,
		"activateCallTime": 4,
		"activateResolvedTime": 48206,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "lifeart.vscode-ember-unstable",
				"_lower": "lifeart.vscode-ember-unstable"
			},
			"activationEvent": "onLanguage:javascript"
		}
	},
	"runtimeErrors": []
}
```
 :warning:

**Comment by lifeart** [comment]
Hi @Depgit could you describe issue itself?

**Comment by Depgit** [comment]
> 
> 
> Hi @Depgit could you describe issue itself?
Hi @lifeart 
In the list of my running extension for vscode... The Git extension
displays "unresponsive "
performance issue

**Comment by lifeart** [comment]
@Depgit could you give more stats on your project? 

how big is it (~ number of files, excluding node_modules), (~ number of adons) 
the action at which the problem occurs?
system configuration (SSD or HDD installed, CPU config)

**Comment by neojp** [comment]
Are you sure this is an error with the extension and not with say Git looking at too many changes in VS Code?

**Comment by lifeart** [comment]
@Depgit could you check version 2.0.17?

**Comment by lifeart** [comment]
@Depgit I'm closing it because there is no response, if it still valid, ping me and we reopen it
