### ISSUE TITLE
Definition for rule 'rule' was not found

### ISSUE THREAD

**Issue by chrismou** [lifeart/vscode-ember#21]
Ive been hitting this linting issue for a while, it shows at the top of every template on this Ember site (screenshot). Today I finally got round to disabling pretty much everything and re-enabling one at a time.  The trigger seems to be when enabling Glimmer Templates Syntax for VS Code along with unstable language server. Specifically after enabling the unstable language server.

I'm not sure if this is an issue with this extension, the language server or my setup, but it's frustrating because the plugin is so useful for finding issues that need fixing, but then it's also got vscode highlighting every single template I open as having "a problem".  Any ideas?

![image](https://user-images.githubusercontent.com/319883/132331951-3a989ab4-d6b8-4590-b228-792807901282.png)

**Comment by lifeart** [comment]
Hi @chrismou! Looks like you have incorrect ember-template-lint rule definition. Could you try run 'yarn lint:hbs' for your project? Do you have same error?

**Comment by lifeart** [comment]
this error hitting you: https://github.com/ember-template-lint/ember-template-lint/blob/33733c0fb7c2bc309dce7c4d9d009f3c68b86622/lib/linter.js#L155

looks like you have rule, named "rule" and it's not defined in ember-template-lint file

**Comment by chrismou** [comment]
Amazing. So it was actually a problem, just a typo in my lint config. And this plugin along with the glimmer syntax plugin was just identifying it :joy: 

Great stuff, thanks for your help and sorry for taking up your time!

![image](https://user-images.githubusercontent.com/319883/132384322-4c16dee4-42b7-42f5-b814-b4b066a87d80.png)
