### ISSUE TITLE
`glimmer-engine` error after fixing helper parentheses deprecation

### ISSUE THREAD

**Issue by charlesfries** [lifeart/vscode-ember#23]
Per this deprecation: https://deprecations.emberjs.com/v3.x/#toc_argument-less-helper-paren-less-invocation

Helpers w/o arguments that are passed to components should be wrapped in parentheses. This template:

`<SomeComponent @arg={{array}} />`

becomes:

`<SomeComponent @arg={{(array)}} />`

However, when I apply this fix to my own app, I see the following error in VSCode's problems drawer:

`Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'OPEN_SEXPR'`

The error goes away if UELS is disabled. Any ideas?

```
DEBUG: -------------------------------
DEBUG: Ember                 : 3.27.5
DEBUG: Ember Data            : 3.27.1
DEBUG: Ember Model Validator : 3.10.0
DEBUG: Ember Simple Auth     : 4.0.0
DEBUG: Model Fragments       : 5.0.0-beta.2
DEBUG: -------------------------------
```

![Screenshot 2021-09-15 154231](https://user-images.githubusercontent.com/2275005/133519406-b59ebf41-1185-4ade-b9fa-1a5bda8fd46b.png)

**Comment by lifeart** [comment]
Hi @charlesfries! Could you share ember-template-lint version you have on project?

**Comment by lifeart** [comment]
It’s error from https://github.com/ember-template-lint/ember-template-lint/issues/1963, can’t fix in uELS level (in long term), but, patch-package or ember-template-recast dependency pinning may help

**Comment by charlesfries** [comment]
`ember-template-lint@3.7.0`

Closing in favor of that other issue. Thanks again @lifeart !
