### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by dcyriller** [lifeart/vscode-ember#3]
I'm trying a fresh install to test a few things 😄. Please note that I'm not a regular VSCode user.

I get this lint error on the first line in every hbs file:
```
ENOENT: no such file or directory, scandir '/Users/cyrille/my-app/file:/Users/cyrille/my-app/app/transactions/index' glimmer-engine
```

Have you already seen this error @lifeart? Do you have any idea of where it could be resolved?

**Comment by lifeart** [comment]
Yeah, I’m hunting for it, likely it comes from ember-template-lint integration, but can’t catch this corner case.

**Comment by dcyriller** [comment]
FYI https://github.com/emberwatch/ember-language-server/pull/329

**Comment by lifeart** [comment]
@dcyriller see https://github.com/lifeart/ember-language-server

**Comment by dcyriller** [comment]
Okaay, I was looking at the wrong repo 🙈.

And I can reproduce this error on the first line with both Unstable and Official VSCode extensions.

**Comment by lifeart** [comment]
@dcyriller is it still actual?

**Comment by dcyriller** [comment]
I don't think so :)
