### ISSUE TITLE
Code folding

### ISSUE THREAD

**Issue by camskene** [lifeart/vscode-ember#31]
The cold-folding arrows in the gutter are no longer visible when the plugin is enabled.

I have version v3.0.18 and VSCode v1.64.2.

If version v3.0.16 is installed the code folding arrows are visible again.

**Comment by Alonski** [comment]
Probably broken by this: https://github.com/lifeart/vscode-ember/commit/31fc7768aa93b225e4449b55b796688ac4cb95fc

**Comment by lifeart** [comment]
@camskene  could you provide some code snippets to test on? 
+ screens of expecting folding and existing


For me - it's visible "on hover" - 
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/1360552/154556375-1f01f79d-2292-46f8-bbd0-c28ad4ad4247.png">
js/ts also, works fine:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/1360552/154556448-c0e3fd56-7085-46a2-b3f8-2ab2e8f358d7.png">

**Comment by lifeart** [comment]
@Alonski is it working for you?

**Comment by camskene** [comment]
This is a hbs file. It is the same with js. First image is v3.0.16, second is v3.0.19. I set the arrows to only show on hover but that didn't fix it.

![image](https://user-images.githubusercontent.com/507499/154569982-e4c4b134-e64a-4ad6-a094-3e86f47d4233.png)

<img width="668" alt="image" src="https://user-images.githubusercontent.com/507499/154570203-ea2845e7-c26b-469c-ad10-a92d2ee49895.png">

**Comment by camskene** [comment]
These are the settings if helpful:
<img width="527" alt="image" src="https://user-images.githubusercontent.com/507499/154570808-83cc9f38-cdae-497d-a151-88ea09f530d1.png">

**Comment by lifeart** [comment]
@camskene how big is your project? (amount of hbs files)

**Comment by camskene** [comment]
I have about 3.5k hbs files.

**Comment by lifeart** [comment]
@camskene looks like language server is busy on templates indexing, foldings should start work once all files will be indexed. Also, it looks like we need to introduce option to disable code folding. Short term solution may be disable template indexing setting els.local.collectTemplateTokens to false + restart vscode

**Comment by camskene** [comment]
@lifeart Can confirm disabling `els.local.collectTemplateTokens` code folding returns. Curiously, I turned it back on and the code folding still worked. This was for hbs files.

Folding not working for js/ts files.

**Comment by lifeart** [comment]
https://github.com/lifeart/ember-language-server/pull/364 created to have ability to disable folding range proivider

**Comment by lifeart** [comment]
Hi @camskene!
Sorry for delay, now you could disable it in uELS extension config:

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/1360552/160555677-6f4e27d9-5bba-4133-ab94-f95d6e78d81d.png">

Let me know if you see other issues. Thank you for report!
