### ISSUE TITLE
Optional chaining syntax highlighting error

### ISSUE THREAD

**Issue by gvocale** [lifeart/vscode-ember#4]
When using `Unstable Ember Language Server`, using optional chaining seem to affect syntax highlighting.

**With Unstable Ember Language Server OFF**

<img width="868" alt="Screen Shot 2020-03-24 at 10 05 11 PM" src="https://user-images.githubusercontent.com/1319291/77494213-915a2d80-6e1b-11ea-87b7-6b946794525c.png">

----

**With Unstable Ember Language Server ON**

<img width="856" alt="Screen Shot 2020-03-24 at 10 04 25 PM" src="https://user-images.githubusercontent.com/1319291/77494244-a46cfd80-6e1b-11ea-98e7-ea9498f18fc3.png">

**Comment by lifeart** [comment]
@gvocale I can't see difference :)
UELS  - don't touching syntax higlighting.

Higlighting - https://github.com/lifeart/vsc-ember-syntax

But, we don't rewrite JS parsing logic, only extend it https://github.com/lifeart/vsc-ember-syntax/blob/master/syntaxes/inline-hbs.json

**Comment by lifeart** [comment]
Now I see, getters color, sample

```ts
import Component from '@glimmer/component';

import { inject as service } from '@ember/service';
interface Args {
    foo?: string
}
export default class HeaderCartComponent extends Component<Args> {
    @service('cart') cart;

    get hasCategory() {
        return this.args.foo?.toString();
    }

    foo() {
        
    }
}
```

it's very strange

**Comment by lifeart** [comment]
Issue appears right after ts language features loading, I think it's related to "ordering", I see same behavour without "UELS", all you need to do  - wait until ts features will be loaded.

**Comment by lifeart** [comment]
![image](https://user-images.githubusercontent.com/1360552/77514597-31e63700-6e88-11ea-8d81-d49c0f0d28f6.png)

(els already loaded ^)


![image](https://user-images.githubusercontent.com/1360552/77514633-3d396280-6e88-11ea-88ce-a84f6664b81b.png)

(ts loaded ^)

**Comment by lifeart** [comment]
disabled UELS and fully loaded TS

![image](https://user-images.githubusercontent.com/1360552/77514850-94d7ce00-6e88-11ea-9f13-ac442994044e.png)

**Comment by lifeart** [comment]
@gvocale try disable UELS and wait for 1 minute, you should see same error

**Comment by gvocale** [comment]
@lifeart my problem is not with the following:
<img width="129" alt="Screen Shot 2020-03-25 at 11 10 58 AM" src="https://user-images.githubusercontent.com/1319291/77551990-5a226580-6e89-11ea-8934-0fac767174c2.png">

But rather with the following:
ON
<img width="125" alt="Screen Shot 2020-03-25 at 11 11 04 AM" src="https://user-images.githubusercontent.com/1319291/77552005-5f7fb000-6e89-11ea-867a-ebbe7d6fd9a3.png">

OFF
<img width="133" alt="Screen Shot 2020-03-25 at 11 11 07 AM" src="https://user-images.githubusercontent.com/1319291/77552485-f8aec680-6e89-11ea-97d0-89e9f5484652.png">


Using optional chaining seem to throw off the color of few lines of code after.

Right now I have UELS off and I haven't been running anymore in the issue. To be honest, other extensions as well were causing the same issue. Right now I have the following extensions enabled:

<img width="659" alt="Screen Shot 2020-03-25 at 11 13 12 AM" src="https://user-images.githubusercontent.com/1319291/77552213-a40b4b80-6e89-11ea-98f7-7d212ffc23fa.png">

**Comment by lifeart** [comment]
It looks like vs code issue itself

**Comment by lifeart** [comment]
closing it as not related to extension
