### ISSUE TITLE
Extension not loading in devcontainer on latest VSCode 1.70.2

### ISSUE THREAD

**Issue by jstys** [lifeart/vscode-ember#40]
Noticed that my handlebars highlighting stopped worked and spent some time debugging the issue.  Seems like the main culprit is VSCode version 1.70.2, I tried different versions of the devcontainer extension on latest VSCode with no effect.

Reverting VSCode back to 1.69.x fixes loading of the extension in devcontainers.

**Comment by lifeart** [comment]
Hi @jstys thank you for report! 
I'm checking 1.71.0 and it seems fine:

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/1360552/188303126-e1060d31-4f38-46e0-b136-4a74b0681358.png">


Could you provide more information with broken code samples?

**Comment by jstys** [comment]
Yes, so for a basic way to reproduce on the latest 1.71.0 release:
1.  Ensure "Remote - Containers" plugin is installed
2. From command palette, choose "Remote Containers - Try a Development Container Sample"
3. Select "Node" and wait for devcontainer to be setup
4. Install the Ember Stable Language Server plugin in the devcontainer
5. Create a basic .hbs file with some handlebars syntax i.e. `{{yield}}`

At this point I notice the .hbs doesn't seem to get registered as handlebars syntax and vscode simply displays it as a regular plain text file.  Goto navigation is also not working.  Note: I don't run into this issue when running vscode normally, only seems to be an issue inside devcontainers which we use pretty heavily for our dev environments.

**Comment by lifeart** [comment]
@jstys could you double check you have https://marketplace.visualstudio.com/items?itemName=lifeart.vscode-glimmer-syntax installed? Ember language server does not have builtin syntax highlighting functionality

**Comment by jstys** [comment]
Okay I think that's what I was looking for.  I've never actually had that extension installed for the multiple years I've used your language server plugin but only recently the syntax highlighting / code navigation stopped working in devcontainers.  Probably safe to close if the language server is not responsible for this behavior.  Thanks for the great ember plugins!
