### ISSUE TITLE
feature request: extract to new component

### ISSUE THREAD

**Issue by IgnaceMaes** [lifeart/vscode-ember#44]
Refactoring components and splitting them up into separate, logical parts is often a struggle as the component gets larger. It would be much helpful if the tooling could support this splitting out of the box (or at least already the template part, the JS is a bit more complex).

With template tag components, components can now be extracted to either a separate file or a new component within the same one.

Here's a similar PR I saw passing by for Volar (Vue's language server) which we could take inspiration from: https://github.com/vuejs/language-tools/pull/2496

**Comment by lifeart** [comment]
Hi @IgnaceMaes! 
Thank you for your report!
We already have this feature (in `els-addon`) https://github.com/lifeart/els-component-extraction-addon

At the moment it's not support `.gts` files, but, I'm open to any PR's

**Comment by IgnaceMaes** [comment]
That's great! I wasn't aware there was a separate plugin for this.

Is there a reason it can't be done within the main ELS plugin itself? I don't see a reason someone wouldn't want this functionality. And having to manually install it outside of a VS Code plugin is quite bad for discoverability.

**Comment by lifeart** [comment]
@IgnaceMaes yep, it's require https://github.com/lifeart/ember-fast-cli to be installed in project. It's not a part of `ember-cli`

**Comment by IgnaceMaes** [comment]
Thanks for clarifying! That's unfortunate, I wonder how it can be made more clear that this functionality exists, as I think a lot of people just wouldn't know.

Closing this issue as I've opened `gjs` support in the other repo.
