### ISSUE TITLE
feature request: .gjs lense support

### ISSUE THREAD

**Issue by Windvis** [lifeart/vscode-ember#46]
It seems that .gjs files don't display the (very useful!) codelenses on top of the editor that made it easy to switch between all related files.

It's not a huge problem since the template and js are now part of a single file, but I think it could still be nice to easily switch to the related test file (or the app reexport for v1 addon components)?

**Comment by lifeart** [comment]
Hi @Windvis, thank you for report, in general, usage logic located here: https://github.com/lifeart/vscode-ember/blob/master/src/usages-provider.ts#L40C17-L40C17

I think we could double check `languageId` for gts/gjs

**Comment by lifeart** [comment]
Additional https://github.com/lifeart/vscode-ember/blob/master/src/lenses.ts#L59C10-L59C27
