### ISSUE TITLE
template-lint in GJS

### ISSUE THREAD

**Issue by ef4** [lifeart/vscode-ember#47]
I noticed that we don't have template-lint feedback when using template tags. I think this is the right repo to implement that feature?

**Comment by lifeart** [comment]
Hi @ef4! Its case for language server, here is may be related conversation: https://github.com/lifeart/ember-language-server/issues/355#issuecomment-1850481169

Could you specify template lint version and package manager?

**Comment by lifeart** [comment]
Hi @ef4, looks like https://github.com/ember-tooling/ember-language-server/pull/400 may fixing you issue.
Closing current ticket for now, let me know if it still appears!
