### ISSUE TITLE
Ember file usage default to `node_modules/.embroider/rewritten_app` copy of component even if excluded

### ISSUE THREAD

**Issue by emattias** [lifeart/vscode-ember#49]
When I press to go to a component that uses the currently active component/template/etc

![CleanShot 2024-11-04 at 16 38 44@2x](https://github.com/user-attachments/assets/01d3fa46-7550-4d0d-b573-f1c4ec6ecd54)

It includes the copy of the component/template/etc that is created in `node_modules/.embroider/rewritten_app/` folder.

And it does this even when I have completely excluded `node_modules/.embroider` from vscode. 

Can an exclude option be added of make the extension follow the vscode exclude setting?

**Comment by lifeart** [comment]
Hi @emattias! Thank you for report!
Im my understanding this change should fix behaviour: https://github.com/ember-tooling/ember-language-server/pull/413
I will let you know once we publish new version of extension

**Comment by lifeart** [comment]
@emattias `EmberTooling.vscode-ember` v3.0.58 published
Let me know if issue still appear.
Actual repo: https://github.com/ember-tooling/vscode-ember/

**Comment by emattias** [comment]
@lifeart So which extension should we use? [Stable Ember Language Server](https://marketplace.visualstudio.com/items?itemName=lifeart.vscode-ember-unstable) or [Ember Language Server](https://marketplace.visualstudio.com/items?itemName=EmberTooling.vscode-ember)? 😅

**Comment by lifeart** [comment]
@emattias now you may count https://marketplace.visualstudio.com/items?itemName=EmberTooling.vscode-ember as upstream.

https://marketplace.visualstudio.com/items?itemName=lifeart.vscode-ember-unstable - will be around for some time (but may be disabled)
