### ISSUE TITLE
Lens feature seems to not work with ember@3.21

### ISSUE THREAD

**Issue by BnitoBzh** [lifeart/vscode-ember#9]

**Comment by BnitoBzh** [comment]
Or probably the last VSCode version (1.49.0 ?)

**Comment by lifeart** [comment]
Hi @BnitoBzh! Thank you for request! Linking: https://github.com/microsoft/vscode/issues/106876

**Comment by lifeart** [comment]
Closing it because it's fixed in vscode `1.50`, @BnitoBzh, thank you for reporting it!
